config/routes.rb
Rails.application.routes.draw do

  get '/welcome', to: 'users#welcome'
  get 'sessions/destroy', as: 'logout'
  post 'sessions/create', as: 'login'
  get 'sessions/create'

  post 'votes/upvote', as: 'upvote'
  post 'votes/downvote', as: 'downvote'

  delete 'boards/:id', to: 'boards#destroy', as: 'delete_board'
  delete 'links/:id', to: 'links#destroy', as: 'delete_link'
  resources :users
  resources :votes
  resources :links
  resources :comments
  resources :boards

  root 'users#welcome'
end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :links

  def self.select_boards
    all.map { |x| [x.category, x.id] }
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :user_id, :link_id, :body
  belongs_to :user
  belongs_to :link
  has_many :votes
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates_presence_of :user_id, :post, :title, :board

  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :board
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :username, :email,
                        :password,
                        :password_confirmation
  has_secure_password
  has_many :links
  has_many :comments
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :comment
  belongs_to :link
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :current_user

  def current_user
    if @current_user.nil?
      if session[:user_id].present?
        @current_user = User.find(session[:user_id])
      end
    else
      @current_user
    end
  end

helper_method :current_user

  def authenticate_user!
    if current_user == nil
      redirect_to login_path, alert: 'You must be logged in.'
    end
  end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def index
    @boards = Board.all.sort_by { |board| board.links.count }.reverse
  end

  def show
    @board = Board.find(params[:id])
    @links = Link.all.where(board_id: params[:id])
  end

  def new
    @board = Board.new
  end

  def create
    Board.create(category: params['/boards/new'][:category])
    redirect_to :back
  end

  # TODO: be able to edit board category names if authorized
  # def edit
  # end

  def destroy
    links = Link.all.where(board_id: params[:id])
    links.each do |link|
      link.comments.each do |comment|
        comment.votes.each do |vote|
          vote.destroy
        end
        comment.destroy
      end
      link.destroy
    end
    Board.find(params[:id]).destroy
    redirect_to :back
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
  end

  def new
    @comments = Comment.new
  end

  def show
    @comments = Comment.find(params[:id])
  end

  # TODO: be able to edit comments if authorized
  def edit
  end

  # TODO: be able to delete comments if authorized
  def destroy
  end

  def create
    @comments = Comment.create(body: params[:comment][:body],
                            user_id: session[:user_id],
                            link_id: params[:comment][:link_id])
    redirect_to :back
  end

private

  def comment_params
    params.require(:comment).permit(:body, :user_id,
                                    :link_id)
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    links = Link.all.reverse
    @links = links.sort_by { |l| l.votes.sort_by { |v| v.upvote } }.reverse
  end

  # TODO: remove logic from link partial
  def show
    @links = Link.find(params[:id])
    @comments = Comment.all.where(link_id: params[:id])
    @comment = Comment.new
    @votes = Link.find(params[:id]).votes

  end

  def new
    @links = Link.new
    @all_boards = Board.select_boards
  end

  def create
    @links = Link.create(title: params[:link][:title], post: params[:link][:post],
                         board_id: params[:link][:board], user_id: session[:user_id] )
    Vote.create(link_id: @links.id)
    redirect_to link_path(@links), notice: 'Post Created'
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    link = Link.find(params[:id])
    link.title = params[:link][:title]
    link.post = params[:link][:post]
    link.save
    redirect_to link_path(link.id)
  end

  def destroy
    Link.find(params[:id]).destroy
    redirect_to links_path
  end

private

  def link_params
    params.require(:link).permit(:title, :post, :user_id,
                                 :board)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @users = User.find_by_email(params[:email])
    if @users  && @users.authenticate(params[:password])
      session[:user_id] = @users.id
      redirect_to root_path, notice: 'Success'
    else
      flash[:alert] = 'Email or password did not match'
      redirect_to new_user_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    users = User.all
    @counter = 1
    @users = users.sort_by { |u| u.links.count }.reverse
  end

  def show
    @users = User.find(params[:id])
    @links = Link.all.where(user_id: params[:id])
    @comments = Comment.all.where(user_id: params[:id])
  end

  def new
    @users = User.new
  end

  def create
    @users = User.create(user_params)
    if @users.save
      session[:user_id] = @users.id
      redirect_to root_path, notice: 'Login Successful'
    else
      flash[:alert] = 'Login Unsuccessful, please try again'
      render new_user_path
    end
  end

  def show_links
    @users = User.find(params[:id]).links
  end
  # TODO: be able to edit users information if authorized
  # def edit
  #   if set_user.id == session[:user_id]
  #     render text: 'success'
  #   else
  #     render text: 'what now'
  #   end
  # end

  # TODO: be able to delete a user account if authorized
  def destroy
  end

  def welcome
    render 'welcome.html.erb'
  end

private

  def set_user
    @users = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password,
                                 :password_confirmation)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def index
  end

  def new
  end

  def show
  end

  def edit
  end

  def destroy
  end

  def upvote
    upvote = Vote.find_by(link_id: params[:link_id]).upvote + 1
    @votes = Vote.find_by(link_id: params[:link_id]).update(upvote: upvote)
    redirect_to :back
  end

  def downvote
    downvote = Vote.find_by(link_id: params[:link_id]).downvote + 1
    @votes = Vote.find_by(link_id: params[:link_id]).update(downvote: downvote)
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/boards/_board.html.erb
<div class="col-md-12">
  <%= "(#{boards.links.count})" %>
  <%= link_to boards.category.titleize, board_path(boards.id) %>
  <% if session[:user_id] == 41 %>
    <%= link_to 'x', "/boards/#{boards.id}", method: :delete, class: 'destroy-btn',
            data: { confirm: "Hit OK to delete this board and all relevant data." } %>
  <% end %>
</div>

app/views/boards/destroy.html.erb
<h1>Coming Soon: delete boards</h1>

app/views/boards/edit.html.erb
<h1>Coming Soon: edit boards</h1>

app/views/boards/index.html.erb
<h1 class="row">All Boards</h1>
<section class="container-fluid">
  <div class="board-index">
    <div class="row">
      <% @boards.each do |board| %>
        <div class="boards">
          <%= render partial: 'board', locals: { boards: board} %>
        </div>
      <% end %>
    </div>
  </div>
</section>
<section class="container-fluid">
  <div class="new-board">
    <div class="row">
      <%= form_for new_board_path do |f| %>
        <%= f.label :category, 'New Category' %>
        <%= f.text_field :category, placeholder: '9 char max',
            maxlength: 9, class: 'text-field' %>
        <%= f.submit 'Create', class: 'submit-btn' %>
      <% end %>
    </div>
  </div>
</section>

app/views/boards/new.html.erb
<h1>Boards#new</h1>
<p>Find me in app/views/boards/new.html.erb</p>

app/views/boards/show.html.erb
<h2><%= "#{@board.category.titleize}(#{@board.links.count})" %></h2>
<p class="board-new">Most Recent Link</p>
<% @links.each do |link| %>
  <%= render partial: 'links/link', locals: { links: link } %>
<% end %>
<div class="row">
  <div class="center-box">
  <%= button_to 'Create New Link', '/links/new', method: :get, class: 'submit-btn' %>
  </div>
</div>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Coming Soon: edit comments</h1>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h2>New Comment</h2>

app/views/comments/show.html.erb
<h2>Comments#show</h2>

<%= @comments.body %>

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Saidit</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag 'https://js.stripe.com/v2/' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class='row'>
      <p class="col-md-2"><%= link_to "Saidit", root_path, class: 'logo' %></p>
      <nav class='col-md-10'>
        <%= link_to 'Users', users_path %>
        <%= link_to 'Links', links_path %>
        <%= link_to 'Boards', boards_path %>
        <% if session[:user_id] %>
          <%=  link_to 'New Link', new_link_path %>
          <%=  link_to 'Logout', logout_path, class: 'session-link' %>
          <%=  link_to @current_user.username.titleize, user_path(@current_user.id),
                                              class: 'session-link' %>
        <% else %>
          <%= link_to 'Sign-Up', new_user_path %>
        <% end %>
        <div class="login-field">
          <% unless session[:user_id] %>
            <div class="login-tag">
              <%= form_tag sessions_create_path do %>
                   Email: <%= text_field_tag :email %>
                Password: <%= password_field_tag :password %>
                          <%= submit_tag "Submit", class: 'submit-btn' %>
              <% end %>
            </div>
          <% end %>
        </div>
      </nav>
    </header>

  <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/links/_comment.html.erb
<div class="comment-box">
  <div class="row">
    <div class="col-md-12">
      <strong><%= comments.user.username %>-</strong>
      <%= comments.body %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 user-cmt">
      <%= comments.created_at.to_formatted_s(:long) %>
    </div>
  </div>
</div>

app/views/links/_link.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="link-show">
      <div>
        <%= link_to links.title.titleize, link_path(links.id) %>
      </div>
      <div><%= links.post %></div>
        --<%= link_to User.find(links.user_id).username.titleize, user_path(links.user_id) %>
      <div class="sub-link-info">
        <div class="links-votes">
          <% if Vote.find_by(link_id: links.id) != nil %>
            <%= Vote.find_by(link_id: links.id).upvote %> Up |
            <%= Vote.find_by(link_id: links.id).downvote %> Down
          <% else %>
            0 Up |
            0 Down
          <% end %>
        </div>
        <div class="edit-btn">
          <% if session[:user_id] == links.user_id %>
            <%= link_to 'EDIT', edit_link_path(links.id) %> |
            <%= link_to 'DELETE', delete_link_path(links.id), method: :delete %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/links/destroy.html.erb
<h1>Coming Soon: delete your links </h1>

app/views/links/edit.html.erb
<h2 class="row"><%= "Edit your link, #{current_user.username.titleize}" %></h2>
<div class="container-fluid">
  <div class="link-area">
    <div class="row">
      <%= form_for @link do |f| %>
      <div class="field col-md-12">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'text-field' %>
      </div>
    </div>
      <div class="row">
        <div class="field col-md-12">
          <%= f.text_area :post, class: 'text-area' %>
        </div>
      </div>
      <div class="row">
        <div class="actions col-md-12">
          <%= f.submit "SAVE", class: 'submit-btn' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/links/index.html.erb
<h1 class="row">All Links</h1>
<% @links.each do |link| %>
  <div class="container-fluid">
    <%= render partial: 'link', locals: { links: link } %>
  </div>
<% end %>

app/views/links/new.html.erb
<h2 class="row">Create a new link, <%= current_user.username.titleize %></h2>
<div class="container-fluid">
  <div class="link-area">
    <div class="row">
      <%= form_for @links do |f| %>
      <div class="field col-md-12">
        <%= f.label :title %>
        <%= f.text_field :title, placeholder: 'Whats up?', class: 'text-field'  %>
      </div>
    </div>
    <div class="row">
      <div class="field col-md-12">
        <%= f.text_area :post, cols: 80, rows: 6,
             placeholder: 'Please explain further', class: 'text-area' %>
      </div>
    </div>
    <div class="row">
      <div class="field col-md-12">
        <%= f.label :category %>
        <%= f.select :board, @all_boards, class: 'cat-drop' %>
      </div>
    </div>
    <div class="row">
      <div class="actions">
        <%= f.submit 'POST', class: 'submit-btn' %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/links/show.html.erb
<h3><%= @links.title.titleize %></h3>
<section>
  <div class="upvote-box"> UP
    <%= button_to @votes[0].upvote, upvote_path(link_id: @links.id), class: 'submit-btn' %>
  </div>
  <div>
    <%= render partial: 'link', locals: { links: @links } %>
  </div>
  <div class="downvote-box"> DOWN
    <%= button_to @votes[0].downvote, downvote_path(link_id: @links.id), class: 'submit-btn' %>
  </div>
  </section>
<section>
  <div>
    <h4><%= "Comments(#{@links.comments.count})" %></h4>
    <% unless @links.comments.count == 0 %>
      <% @comments.each do |comment| %>
        <%= render partial: 'comment', locals: { comments: comment } %>
      <% end %>
    <% end %>
  </div>
  <div>
    <%= form_for @comment do |f| %>
      <div class="field">
        <%= f.text_area :body, rows: 4, cols: 80, placeholder: 'Put your comment here, yo' %>
        <%= f.hidden_field :link_id, value: @links.id %>
      </div>
      <div class="actions">
        <%= f.submit 'Comment', class: 'submit-btn' %>
      </div>
    <% end %>
  </div>
</section>

app/views/users/_login.html.erb
<% form_tag("/sessions/create", method: "post") do %>
  <%= label_tag(:email) %>
  <%= text_field_tag(:email) %>
  <%= label_tag(:password) %>
  <%= password_field_tag(:password) %>
  <%= submit_tag("Login") %>
<% end %>

app/views/users/_signup.html.erb
<%= form_for(@users) do |f| %>
  <% if @users.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@users.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @users.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container-fluid">
    <div class="row">
      <div class="field col-md-12">
        <%= f.label :username %><br>
        <%= f.text_field :username, class: 'text-field-signup' %>
      </div>
    </div>
    <div class="row">
      <div class="field col-md-12">
        <%= f.label :email %><br>
        <%= f.text_field :email, class: 'text-field-signup'  %>
      </div>
    </div>
    <div class="row">
      <div class="field col-md-12">
        <%= f.label :password %><br>
        <%= f.password_field :password, class: 'text-field-signup'  %>
      </div>
    </div>
    <div class="row">
      <div class="field col-md-12">
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation, class: 'text-field-signup'  %>
      </div>
    </div>
    <div class="row">
      <div class="actions col-md-12">
        <%= f.submit 'Sign-Up', class: 'submit-btn' %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<div class="col-md-4">
  <section class='container-fluid'>
    <div class="user-index-box">
      <div class="user-index-info">
        <div class="row">
          <span class="glyphicon glyphicon-user col-md-12" aria-hidden="true">
            <%= link_to user.username.titleize, user_path(user) %>
          </span>
        </div>
        <div class="col-md-12 email">
          <%= mail_to user.email %>
        </div>
        <div class="row">
          <div class="col-md-12">
            <span class="badge">
              <%= user.links.count %> Link(s) Posted <%= "| # #{@counter}" %>
              <% @counter += 1 %>
            </span>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/users/destroy.html.erb
<h1>Coming Soon: Delete your account</h1>

app/views/users/edit.html.erb
<h1>Coming Soon: Edit Profile - @users.username.titleize </h1>

app/views/users/index.html.erb
<h2 class="row">All Users</h2>
<section class="row">
  <% @users.each do |user| %>
    <%= render partial: 'user', locals: { user: user } %>
  <% end %>
</section>

app/views/users/new.html.erb
<h2 class="row">Create an Account</h2>
<div class="container-fluid">
 <%= render 'signup' %>
</div>

app/views/users/show.html.erb
<h2 class="row"><%= "#{@users.username.titleize}'s Profile" %></h2>
<section class="container-fluid">
  <div class="user-profile">
    <div class="user-profile-contents row">
      <p class="col-md-12"><%= mail_to @users.email %></p>
      <p class="col-md-12">Total Links: <%= @users.links.count %></p>
      <p class="col-md-12">Votes Cast: <%= @users.votes.count %></p>
      <p class="col-md-12">Comments Made: <%= @users.comments.count %></p>
    </div>
  </div>
</section>
<section class='container-fluid'>
  <h3 class="row">Links</h3>
    <div class="row">
      <% @links.each do |link| %>
        <%= render partial: 'links/link', locals: { links: link } %>
      <% end %>
    </div>
  <h4 class="row">Comments</h4>
  <div class="container">
    <% @comments.each do |comment| %>
      <%= render partial: 'links/comment', locals: { comments: comment } %>
    <% end %>
  </div>
</section>

app/views/users/show_id.html.erb
<h1>Users#show_id</h1>
<p>Find me in app/views/users/show_id.html.erb</p>

app/views/users/show_links.html.erb
<h1>Users#show_id</h1>
<p>Find me in app/views/users/show_id.html.erb</p>

app/views/users/welcome.html.erb
<section class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="welcome">
        <h1>Welcome to Saidit</h1>
        <h3>The site created to replace reddit</h3>
        <h4><%= link_to 'https://github.com/BenHand/saidit', 'Github for saidit' %></h4>
      </div>
    </div>
  </div>
</section>

app/views/votes/destroy.html.erb
<h1>Votes#destroy</h1>
<p>Find me in app/views/votes/destroy.html.erb</p>

app/views/votes/edit.html.erb
<h1>Votes#edit</h1>
<p>Find me in app/views/votes/edit.html.erb</p>

app/views/votes/index.html.erb
<h1>Votes#index</h1>
<p>Find me in app/views/votes/index.html.erb</p>

app/views/votes/new.html.erb
<h1>Votes#new</h1>
<p>Find me in app/views/votes/new.html.erb</p>

app/views/votes/show.html.erb
<h1>Votes#show</h1>
<p>Find me in app/views/votes/show.html.erb</p>